# Generated by Django 5.1.2 on 2024-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_image_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_number',
            field=models.CharField(default=1234567890, max_length=15),
            preserve_default=False,
        ),
    ]
